config/routes.rb
Rails.application.routes.draw do
  resources :hollers
  #get 'home/index'
  get 'home/profile'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/holler.rb
class Holler < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hollers_controller.rb
class HollersController < ApplicationController
  before_action :set_holler, only: %i[ show edit update destroy ]

  # GET /hollers or /hollers.json
  def index
    @hollers = Holler.all
  end

  # GET /hollers/1 or /hollers/1.json
  def show
  end

  # GET /hollers/new
  def new
    @holler = Holler.new
  end

  # GET /hollers/1/edit
  def edit
  end

  # POST /hollers or /hollers.json
  def create
    @holler = Holler.new(holler_params)

    respond_to do |format|
      if @holler.save
        format.html { redirect_to holler_url(@holler), notice: "Holler was successfully created." }
        format.json { render :show, status: :created, location: @holler }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @holler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hollers/1 or /hollers/1.json
  def update
    respond_to do |format|
      if @holler.update(holler_params)
        format.html { redirect_to holler_url(@holler), notice: "Holler was successfully updated." }
        format.json { render :show, status: :ok, location: @holler }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @holler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hollers/1 or /hollers/1.json
  def destroy
    @holler.destroy

    respond_to do |format|
      format.html { redirect_to hollers_url, notice: "Holler was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holler
      @holler = Holler.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def holler_params
      params.require(:holler).permit(:title, :subtitle, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hollers_helper.rb
module HollersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/hollers/_form.html.erb
<%= form_with(model: holler) do |form| %>
  <% if holler.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(holler.errors.count, "error") %> prohibited this holler from being saved:</h2>

      <ul>
        <% holler.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <div class = "field form-group">
      <% form.label :heading, style: "display: block" %>
      <%= form.text_field :title, class: "form-control", placeholder: "Heading" %>
    </div>

    <div class = "field form-group">
      <% form.label :subheading, style: "display: block" %>
      <%= form.text_field :subtitle, class: "form-control", placeholder: "subheading" %>
    </div>

    <div class = "field form-group">
      <% form.label :message, style: "display: block" %>
      <%= form.text_area :message, class: "form-control",placeholder: "Message" %>
    </div>
    <br/>
    <div>
      <%= form.submit class: "btn btn-info" %>
    </div>
  </div>
<% end %>

app/views/hollers/_holler.html.erb
<div id="<%= dom_id holler %>" class="card" style="width: 30rem;">
  
  <div class="card-body"> 
    <%# <%= image_tag @holler.avatar%>
    <%# <%= image_tag @holler.avatar if @holler.avatar.attached? %>
    <%# <%= @holler.avatar %>
    <%# <%= render @holler%>
    <h5 class="card-title"><%= holler.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= holler.subtitle %></h6>
    <p class="card-text"><%= holler.message %></p>
    <a class="link-menu">
      <svg width="1.5em" height="1.5em" viewBox="0 -2 17 17" class="bi bi-arrow-return-right"
            fill="lightgrey" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M1.5 1.5A.5.5 0 0 0 1 2v4.8a2.5 2.5 0 0 0 2.5 2.5h9.793l-3.347 3.346a.5.5 0 0 0 .708.708l4.2-4.2a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 8.3H3.5A1.5 1.5 0 0 1 2 6.8V2a.5.5 0 0 0-.5-.5z"/>
      </svg>
      </a>
      <a class="link-menu">
      <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-stars"
            fill="lightgrey" xmlns="http://www.w3.org/2000/svg">
             <path d="M7.657 6.247c.11-.33.576-.33.686 0l.645 1.937a2.89 2.89 0 0 0 1.829 1.828l1.936.645c.33.11.33.576 0 .686l-1.937.645a2.89 2.89 0 0 0-1.828 1.829l-.645 1.936a.361.361 0 0 1-.686 0l-.645-1.937a2.89 2.89 0 0 0-1.828-1.828l-1.937-.645a.361.361 0 0 1 0-.686l1.937-.645a2.89 2.89 0 0 0 1.828-1.828l.645-1.937zM3.794 1.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387A1.734 1.734 0 0 0 4.593 5.69l-.387 1.162a.217.217 0 0 1-.412 0L3.407 5.69A1.734 1.734 0 0 0 2.31 4.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387A1.734 1.734 0 0 0 3.407 2.31l.387-1.162zM10.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732L9.1 2.137a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L10.863.1z"/>
      </svg>
      </a>
    <%# </li> %>
    
    &nbsp;
    
    
    <%# <%= link_to "Show Holler", holler %>
    
    <%# <a href="#" class="card-link">Card link</a> %>
    <%# <a href="#" class="card-link">Another link</a> %>
 
  </div>
</div>
<br/>

<% if false %>
<div id="<%= dom_id holler %>">
  <p>
    <strong>Title:</strong>
    <%= holler.title %>
  </p>

  <p>
    <strong>Subtitle:</strong>
    <%= holler.subtitle %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= holler.message %>
  </p>
  <% end %>

app/views/hollers/edit.html.erb
<br/>
<h1>Edit holler</h1>

<%= render "form", holler: @holler %>

<br>
<%# <div class = "text-center"> %>
<div>
  <%= link_to "Back", hollers_path, class: "btn btn-info" %>
  <%= link_to "Show Holler", @holler, class: "btn btn-info" %>&nbsp;
</div>

app/views/hollers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Holler Dashboard</h1>

<div id="hollers">
  <% @hollers.each do |holler| %>
    <%= render holler %>
    <p>
      <%= link_to "Show Holler", holler, class: "btn btn-info" %>&nbsp;
      <%= link_to "New holler", new_holler_path, class: "btn btn-info" %>
    </p>
  <% end %>
</div>

app/views/hollers/new.html.erb
<br/>
<h1>New holler</h1>

<br/>
<%= render "form", holler: @holler %>

<br>

<div>
  <%= link_to "Back to hollers", hollers_path, class: "btn btn-info" %>
</div>

app/views/hollers/show.html.erb
<p style="color: green"><%= notice %></p>
<br/>
<div class="mx-auto" style="width: 400px;">
  <%# <div class = "text-center"> %>
  <br/>
  <%# <div class="mx-auto" style="width: 400px;"> %>
  <div>
    <%= link_to "Back", hollers_path, class: "btn btn-info" %> &nbsp;
    <%= link_to "Edit", edit_holler_path(@holler), class: "btn btn-info" %> &nbsp;
    <%# <%= link_to "Show holler", holler, class: "btn btn-info" %>
  </div>
  <br/>
  <div>
    <%= render @holler %>
  </div>
  
  
  <div>
  <%= button_to "Delete", @holler, method: :delete, class: "btn btn-info" %>
  </div>
</div>

app/views/home/_footer.html.erb
<%# <!-- Footer -->
<footer class="page-footer font-small cyan darken-3">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Grid row-->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-12 py-5">
        <div class="mb-5 flex-center">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Pinterest-->
          <a class="pin-ic">
            <i class="fab fa-pinterest fa-lg white-text fa-2x"> </i>
          </a>
        </div>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2022 Copyright Holler
    <br/>Contact: Hola@Holler.com (not a real email)
    <%# <a href=""> Holler</a> %>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <li li class="list-inline-item">
        <svg width="1.5em" height="1.5em" viewBox="0 0 16 17" class="bi bi-brightness-high-fill"
            fill="white" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 8a4 4 0 1 1-8 0 4 4 0 0 1 8 0zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
        </svg>
    </li>
    <%= link_to "Holler", root_path , class:"navbar-brand" %>
    <%# <a class="navbar-brand" href="#"><img src="../app/assets/images/brightness-high-fill.svg" width="30" height="30" class="d-inline-block align-top" alt=""> Holler</a> %>
    <%# <a class="navbar-brand" href="#">Holler</a> %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <div class="d-flex flex-row">
        <ul class="list-inline m-0">
            <li class="list-inline-item">
                <a href="/home/profile" class="link-menu">
                    <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-person"
                        fill="white" xmlns="http://www.w3.org/2000/svg">
                        <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                    </svg>
                </a>
            </li>
            <li class="list-inline-item ml-2">
                <a href="#" class="link-menu">
                    <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-chat-dots"
                        fill="white" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                        <path d="m2.165 15.803.02-.004c1.83-.363 2.948-.842 3.468-1.105A9.06 9.06 0 0 0 8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6a10.437 10.437 0 0 1-.524 2.318l-.003.011a10.722 10.722 0 0 1-.244.637c-.079.186.074.394.273.362a21.673 21.673 0 0 0 .693-.125zm.8-3.108a1 1 0 0 0-.287-.801C1.618 10.83 1 9.468 1 8c0-3.192 3.004-6 7-6s7 2.808 7 6c0 3.193-3.004 6-7 6a8.06 8.06 0 0 1-2.088-.272 1 1 0 0 0-.711.074c-.387.196-1.24.57-2.634.893a10.97 10.97 0 0 0 .398-2z"/>
                    </svg>
                </a>
            </li>
            <li class="list-inline-item ml-2">
                <a href="#" class="link-menu">
                    <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-bookmark-heart"
                        fill="white" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M8 4.41c1.387-1.425 4.854 1.07 0 4.277C3.146 5.48 6.613 2.986 8 4.412z"/>
                        <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
                    </svg>
                </a>
            </li>
        </ul>
        &nbsp;&nbsp;&nbsp;  
    </div>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <a href="/hollers/new" button class="btn btn-outline-success my-2 my-sm-1" type="submit">Hola!</a>
    </form>
    
  </div>
</nav>

app/views/home/index.html.erb
<div class = "text-center">
<%# class="h-100 row align-items-center" %>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h1>Hola!</h1>
    <p>Welcome to Holler!</p>
    <a href="/hollers/" class="btn btn-info">Check out Holler</a>
    <br/><br/>
<div>

<%# <p>Find me in app/views/home/index.html.erb</p> %>

app/views/home/profile.html.erb
<br/>
    <h1>Profile Page</h1>
    <p>Hola! Welcome to my page!<br/>
    This project was created on Ruby on Rails!</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Welcome to Holler</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render 'home/header'%>
    <div class = "container">
    <%= yield %>
    </div>
    <%= render 'home/footer'%>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>